import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import Nav from '@/components/Nav'
import { WorkoutProvider } from '@/context/WorkoutContext'
import { Toaster } from 'sonner'
import { Check, X } from 'lucide-react'
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-oswald",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "FITLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <WorkoutProvider>
          <header className="shrink-0">
            <Nav/>
          </header>
          {children}
        </WorkoutProvider>
        <Toaster
          position="top-right"
          toastOptions={{
            classNames: {
              toast: 'w-fit! bg-[#1E2330]! border-[#9CA3AF]! text-[#E5E7EB]!'
            }
          }}
          icons={{
            success: <Check size={18} className="text-white p-0.5 bg-green-300 rounded-full"/>,
            error: <X size={20} className="text-white p-0.5 bg-red-400 rounded-full"/>
          }}
        />
      </body>
    </html>
  );
}
