import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import Nav from '@/components/Nav'
import Toast from "@/components/Toast"
import Footer from "@/components/Footer";
import { WorkoutProvider } from '@/context/WorkoutContext'
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-oswald",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "FITLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <WorkoutProvider>
          <header className="shrink-0">
            <Nav/>
          </header>
          {children}
        </WorkoutProvider>
        <Footer/>
        <Toast/>
      </body>
    </html>
  );
}
